apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-automation-suite
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: DevOps Automation Suite
  
  # Allow manifests to deploy from any Git repo
  sourceRepos:
  - '*'
  
  # Only deploy to the same cluster
  destinations:
  - namespace: app-namespace
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  
  # Permissions within the project
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  
  # Prevent manifest deletion during sync
  orphanedResources:
    warn: true