apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app-namespace
  labels:
    app: sample-app
    environment: dev
type: Opaque
data:
  # These are example values. In production, use proper secret management
  DB_PASSWORD: cGFzc3dvcmQxMjM= # base64 encoded "password123"
  API_KEY: ZXhhbXBsZWFwaWtleTE= # base64 encoded "exampleapikey1"
  JWT_SECRET: and0c2VjcmV0a2V5MTIz # base64 encoded "jwtsecretkey123"

---